### ISSUE TITLE
id property of typeAnnotation of NullableTypeAnnotation is not always defined

### ISSUE THREAD

**Issue by jessebeach** [relayjs/eslint-plugin-relay#9]
```
STDERR
     ../eslint-plugin-relay/eslint-plugin-relay.js:330
          propTypeProperty.value.typeAnnotation.id.name === type

TypeError: Cannot read property 'name' of undefined
at validateObjectTypeAnnotation (../eslint-plugin-relay/eslint-plugin-relay.js:330:45)
at Program:exit.expectedTypes.forEach.type (../eslint-plugin-relay/eslint-plugin-relay.js:741:23)
at Array.forEach (native)
at EventEmitter.Program:exit (../eslint-plugin-relay/eslint-plugin-relay.js:687:25)
at emitOne (events.js:120:20)
at EventEmitter.emit (events.js:210:7)
at NodeEventGenerator.leaveNode (../eslint/lib/util/node-event-generator.js:49:22)

```

Concerning this bit of code here:

```
if (
    propTypeProperty.value.type === 'NullableTypeAnnotation' &&
    propTypeProperty.value.typeAnnotation.id.name === type
  ) {
    return true;
  }
```

**Comment by jessebeach** [comment]
It probably needs a null-safe drilldown into this member expression chain to get `name`.
